LANGUAGES = ["English", "العربية"]

TRANSLATIONS = {
    "English": {
        "app_title": "Project Risk Analyzer",
        "app_subtitle": "AI-powered project intelligence platform for predictive risk analysis, delivery forecasting, and executive decision support.",
        "language": "Language / اللغة",
        "theme": "Dark mode",
        "project_inputs": "Control Panel",
        "project_information": "Project Information",
        "risk_parameters": "Risk Parameters",
        "resource_settings": "Resource Settings",
        "forecast_controls": "Forecast Controls",
        "upload_title": "Project Intelligence Intake",
        "upload_help": "Upload a project proposal, charter, risk register, schedule, budget file, CSV, PDF, DOCX, TXT, or XLSX.",
        "uploaded": "Uploaded file",
        "clear_file": "Clear loaded file",
        "processing": "Processing project file and analytics model...",
        "run_analysis": "Run AI Analysis",
        "refresh_ai": "Refresh AI Insights",
        "empty_title": "Demo analytics are active until a project file is uploaded.",
        "empty_body": "Upload a file to replace the synthetic portfolio scenario with evidence-based project intelligence.",
        "executive_overview": "Executive Overview",
        "risk_analysis": "Risk Analysis",
        "forecasting": "Predictive Delivery Analytics",
        "schedule_control": "Schedule Control",
        "evm": "Earned Value Management",
        "resource_analytics": "Resource Analytics",
        "ai_insights": "Executive Insights Engine",
        "reports": "Reports",
        "overall_risk": "Overall Risk Score",
        "budget_health": "Budget Health",
        "schedule_health": "Schedule Health",
        "critical_tasks": "Critical Tasks",
        "predicted_delay": "Predicted Delay",
        "ai_confidence": "AI Confidence",
        "project_status": "Project Status",
        "risk_signals": "Risk Signals",
        "category": "Category",
        "score": "Score",
        "probability": "Probability",
        "impact": "Impact",
        "financial_impact": "Financial Impact",
        "risk_heatmap": "Enterprise Risk Exposure Matrix",
        "risk_breakdown": "Risk Category Breakdown",
        "timeline": "Project Timeline",
        "forecast": "Predictive Delivery Forecast",
        "resource_load": "Resource Load",
        "spi": "Schedule Performance Index",
        "cpi": "Cost Performance Index",
        "budget_variance": "Predicted Budget Variance",
        "root_cause": "Root Cause",
        "recommended_actions": "Recommended Actions",
        "priority_level": "Priority Level",
        "impact_reduction": "Estimated Impact Reduction",
        "confidence_score": "Confidence Score",
        "executive_summary": "Executive Summary",
        "recommendations": "Recommendations",
        "download_pdf": "Download Executive PDF",
        "brand_caption": "Predictive analytics for smarter project delivery",
        "assistant_label": "AI Assistant",
        "milestones": "Milestone Tracking",
        "risk_radar": "Risk Radar",
        "critical_ranking": "Critical Task Ranking",
        "budget_waterfall": "Budget Variance Waterfall",
        "portfolio_signal": "Portfolio Signal",
        "chat_title": "Ask the AI Risk Assistant",
        "chat_placeholder": "Ask about risks, delays, budget, scope, or mitigation...",
        "chat_button": "Ask",
        "no_ai": "AI insights are not available yet. Check your API key or refresh the analysis.",
        "stable": "Stable",
        "medium": "Moderate Risk",
        "high": "High Risk",
        "critical": "Critical",
        "duration": "Delivery Horizon",
        "budget": "Investment Tier",
        "team_size": "Team Size",
        "complexity": "Project Complexity",
        "stakeholder_engagement": "Stakeholder Engagement",
        "schedule_pressure": "Schedule Pressure",
        "resource_availability": "Resource Availability",
        "scope_clarity": "Scope Clarity",
        "evm_dashboard": "Earned Value Dashboard",
        "evm_source_data": "EVM Source Data",
        "evm_values": "Earned Value Baseline",
        "evm_variances": "Schedule and Cost Variance",
        "evm_indices": "Performance Indices",
        "evm_forecast": "Completion Forecast",
        "bac": "Budget at Completion",
        "pv": "Planned Value",
        "ev": "Earned Value",
        "ac": "Actual Cost",
        "sv": "Schedule Variance",
        "cv": "Cost Variance",
        "eac": "Estimate at Completion",
        "etc": "Estimate to Complete",
        "vac": "Variance at Completion",
        "tcpi": "To-Complete Performance Index",
        "percent_complete": "Percent Complete",
        "traffic_light": "Traffic Light",
        "source_confidence": "Source Confidence",
        "missing_evm_data": "Missing EVM source data",
        "evm_assumptions": "EVM Assumptions and Data Gaps",
        "schedule_control_dashboard": "Schedule Control Dashboard",
        "critical_path": "Critical Path",
        "float_analysis": "Float Analysis",
        "total_float": "Total Float",
        "s_curve": "S-Curve",
        "milestone_slippage": "Milestone Slippage",
        "schedule_forecast": "Schedule Forecast",
        "forecast_finish": "Forecast Finish Date",
        "baseline_finish": "Baseline Finish Date",
        "forecast_delay_days": "Forecast Delay Days",
        "schedule_traffic": "Schedule Health",
        "not_enough_schedule_data": "Not enough schedule data",
        "schedule_assumptions": "Schedule Assumptions and Data Gaps",
    },
    "العربية": {
        "app_title": "Project Risk Analyzer",
        "app_subtitle": "منصة ذكاء مشاريع مدعومة بالذكاء الاصطناعي لتحليل المخاطر التنبؤية، توقعات التسليم، ودعم القرار التنفيذي.",
        "language": "Language / اللغة",
        "theme": "الوضع الداكن",
        "project_inputs": "لوحة التحكم",
        "project_information": "معلومات المشروع",
        "risk_parameters": "معايير المخاطر",
        "resource_settings": "إعدادات الموارد",
        "forecast_controls": "إعدادات التنبؤ",
        "upload_title": "مدخل ذكاء المشروع",
        "upload_help": "ارفع مقترح المشروع أو الميثاق أو سجل المخاطر أو الجدول أو الميزانية بصيغة CSV أو PDF أو DOCX أو TXT أو XLSX.",
        "uploaded": "تم رفع الملف",
        "clear_file": "مسح الملف المحمل",
        "processing": "جاري معالجة ملف المشروع ونموذج التحليلات...",
        "run_analysis": "تشغيل تحليل الذكاء الاصطناعي",
        "refresh_ai": "تحديث الرؤى الذكية",
        "empty_title": "تحليلات تجريبية نشطة إلى حين رفع ملف المشروع.",
        "empty_body": "ارفع ملفاً لاستبدال السيناريو التجريبي بتحليل مشروع مبني على الأدلة.",
        "executive_overview": "الملخص التنفيذي",
        "risk_analysis": "تحليل المخاطر",
        "forecasting": "تحليلات التسليم التنبؤية",
        "schedule_control": "ضبط الجدول الزمني",
        "evm": "إدارة القيمة المكتسبة",
        "resource_analytics": "تحليلات الموارد",
        "ai_insights": "محرك الرؤى التنفيذية",
        "reports": "التقارير",
        "overall_risk": "مؤشر المخاطر العام",
        "budget_health": "صحة الميزانية",
        "schedule_health": "صحة الجدول",
        "critical_tasks": "المهام الحرجة",
        "predicted_delay": "التأخير المتوقع",
        "ai_confidence": "ثقة الذكاء الاصطناعي",
        "project_status": "حالة المشروع",
        "risk_signals": "إشارات المخاطر",
        "category": "الفئة",
        "score": "المؤشر",
        "probability": "الاحتمالية",
        "impact": "الأثر",
        "financial_impact": "الأثر المالي",
        "risk_heatmap": "مصفوفة التعرض للمخاطر",
        "risk_breakdown": "تصنيف فئات المخاطر",
        "timeline": "الجدول الزمني للمشروع",
        "forecast": "توقعات التسليم التنبؤية",
        "resource_load": "تحميل الموارد",
        "spi": "مؤشر أداء الجدول",
        "cpi": "مؤشر أداء التكلفة",
        "budget_variance": "الانحراف المالي المتوقع",
        "root_cause": "السبب الجذري",
        "recommended_actions": "الإجراءات الموصى بها",
        "priority_level": "مستوى الأولوية",
        "impact_reduction": "خفض الأثر المتوقع",
        "confidence_score": "درجة الثقة",
        "executive_summary": "الملخص التنفيذي",
        "recommendations": "التوصيات",
        "download_pdf": "تحميل التقرير التنفيذي PDF",
        "brand_caption": "تحليلات تنبؤية لتسليم مشاريع أكثر ذكاءً",
        "assistant_label": "المساعد الذكي",
        "milestones": "تتبع المعالم",
        "risk_radar": "رادار المخاطر",
        "critical_ranking": "ترتيب المهام الحرجة",
        "budget_waterfall": "تحليل الانحراف المالي",
        "portfolio_signal": "إشارة المحفظة",
        "chat_title": "اسأل مساعد مخاطر المشروع",
        "chat_placeholder": "اسأل عن المخاطر أو التأخير أو الميزانية أو النطاق أو المعالجات...",
        "chat_button": "اسأل",
        "no_ai": "الرؤى الذكية غير متاحة بعد. تحقق من مفتاح API أو حدّث التحليل.",
        "stable": "مستقر",
        "medium": "مخاطر متوسطة",
        "high": "مخاطر عالية",
        "critical": "حرج",
        "duration": "أفق التسليم",
        "budget": "فئة الاستثمار",
        "team_size": "حجم الفريق",
        "complexity": "تعقيد المشروع",
        "stakeholder_engagement": "تفاعل أصحاب المصلحة",
        "schedule_pressure": "ضغط الجدول الزمني",
        "resource_availability": "توفر الموارد",
        "scope_clarity": "وضوح نطاق العمل",
        "evm_dashboard": "لوحة القيمة المكتسبة",
        "evm_source_data": "بيانات مصدر القيمة المكتسبة",
        "evm_values": "خط أساس القيمة المكتسبة",
        "evm_variances": "انحراف الجدول والتكلفة",
        "evm_indices": "مؤشرات الأداء",
        "evm_forecast": "توقعات الإنجاز",
        "bac": "الميزانية عند الإنجاز",
        "pv": "القيمة المخططة",
        "ev": "القيمة المكتسبة",
        "ac": "التكلفة الفعلية",
        "sv": "انحراف الجدول",
        "cv": "انحراف التكلفة",
        "eac": "التقدير عند الإنجاز",
        "etc": "التقدير للإكمال",
        "vac": "الانحراف عند الإنجاز",
        "tcpi": "مؤشر الأداء للإكمال",
        "percent_complete": "نسبة الإنجاز",
        "traffic_light": "مؤشر الحالة",
        "source_confidence": "ثقة المصدر",
        "missing_evm_data": "بيانات EVM المفقودة",
        "evm_assumptions": "افتراضات وفجوات القيمة المكتسبة",
        "schedule_control_dashboard": "لوحة ضبط الجدول الزمني",
        "critical_path": "المسار الحرج",
        "float_analysis": "تحليل السماحية الزمنية",
        "total_float": "السماحية الزمنية الكلية",
        "s_curve": "منحنى S",
        "milestone_slippage": "انزلاق المعالم",
        "schedule_forecast": "توقعات الجدول الزمني",
        "forecast_finish": "تاريخ الانتهاء المتوقع",
        "baseline_finish": "تاريخ الانتهاء الأساسي",
        "forecast_delay_days": "أيام التأخير المتوقعة",
        "schedule_traffic": "صحة الجدول الزمني",
        "not_enough_schedule_data": "لا توجد بيانات كافية للجدول الزمني",
        "schedule_assumptions": "افتراضات وفجوات الجدول الزمني",
    },
}


def t(language, key):
    return TRANSLATIONS[language].get(key, TRANSLATIONS["English"].get(key, key))


def direction(language):
    return "rtl" if language == "العربية" else "ltr"
